Mobile menu
spydaspider/microverse-projects pull request #6
Opened 2022-07-19 09:32 UTC by spydaspider

# Mobile Menu for my Portfolio
# On small screens like mobile, there is a mobile menu that displays menu of the links to navigate the pages.  
- [ ] Bug fix (unexpected generic font-family).
- [ ] New feature ( font-family; Poppins, Arial, Helvetica, sans-serif;)
- [ ] New files (.eslintrc.json)
  - [ ] Run local stylelint config command(npx stylelint "**/*.{css,scss}" --fix  after changing the font.
# Checklist
 [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2022-07-19 11:22 UTC, muneebulrehman requested changes
Hi @spydaspider , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Descriptive PR
- Good commit messages

## Required Changes ♻️

- [ ] Kindly add the linter files for javascript.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-19 11:22 UTC, muneebulrehman commented on index.html
> +
Kindly follow the margin/paddings as per the Figma template.
| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/33268927/179738056-03384a82-dc61-4bb1-bed5-6a43add0e460.png) | ![image](https://user-images.githubusercontent.com/33268927/179737955-35514aaa-0fed-4192-90ac-7f72c6307794.png) |

2022-07-19 11:22 UTC, muneebulrehman commented on index.html
> +          <li class = "nav-item"><a href = "#headline">Portfolio</a></li>
In the mobile menu, when I click on the portfolio link, it doesn't take me to the portfolio section but to the top of the page. Consider fixing it.

2022-07-19 11:26 UTC, spydaspider commented
Thank you.

On Tue, 19 Jul 2022, 11:22 am MUNEEB UL REHMAN, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @spydaspider <https://github.com/spydaspider> ,
>
> Good job so far! I see you put a lot of effort into this project. However,
> there are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
>    - Descriptive PR
>    - Good commit messages
>
> Required Changes ♻️
>
>    - Kindly add the linter files for javascript.
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/spydaspider/microverse-projects/pull/6#discussion_r924373619>
> :
>
> > +      <div class = "mobile-menu">
>
> +        <ul class = "nav-menu">
>
> +          <li class = "nav-item"><a href = "#headline">Portfolio</a></li>
>
> +          <li class = "nav-item"><a href = "#section-5">About</a></li>
>
> +          <li class = "nav-item"><a href = "#section-7">Contact</a></li>
>
> +        </ul>
>
> +        <div class="x-icon x-style">
>
> +          <span class = "bar-x"></span>
>
> +          <span class = "bar-x"></span>
>
> +          <span class = "bar-x"></span>
>
> +
>
>
> Kindly follow the margin/paddings as per the Figma template.
> Your design Figma design
> [image: image]
> <https://user-images.githubusercontent.com/33268927/179738056-03384a82-dc61-4bb1-bed5-6a43add0e460.png> [image:
> image]
> <https://user-images.githubusercontent.com/33268927/179737955-35514aaa-0fed-4192-90ac-7f72c6307794.png>
> ------------------------------
>
> In index.html
> <https://github.com/spydaspider/microverse-projects/pull/6#discussion_r924374901>
> :
>
> > @@ -11,15 +11,21 @@
>
>      <header id="headline">
>
>        <nav class="nav-container">
>
>          <div class="logo-text"><a href="#">Spyda</a></div>
>
> -        <div class="right-logo">
>
> -          <img
>
> -            src="images/menu-icon.png"
>
> -            alt="Menu Icon for toggle on small screens"
>
> -          />
>
> +      <div class = "mobile-menu">
>
> +        <ul class = "nav-menu">
>
> +          <li class = "nav-item"><a href = "#headline">Portfolio</a></li>
>
>
> In the mobile menu, when I click on the portfolio link, it doesn't take me
> to the portfolio section but to the top of the page. Consider fixing it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spydaspider/microverse-projects/pull/6#pullrequestreview-1043256625>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXXCN5NZWPROQGVXAEXP2GLVU2FXPANCNFSM537I6CIQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-19 17:28 UTC, mwanawabangona approved these changes
Hi @spydaspider @Moathal,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implimenting the requested changes !! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-19 17:30 UTC, spydaspider commented
Thank you! You guys have been of great help.


On Tue, 19 Jul 2022, 5:28 pm mwanawabangona, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @spydaspider <https://github.com/spydaspider> @Moathal
> <https://github.com/Moathal>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations!
>
> <https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966>
> Highlights
>
>    - No linter errors ✔️
>    - Repo looks professional 💼
>    - Solid pull request scroll
>    - Good quality commits
>    - Good job implimenting the requested changes !! 👏 👏 👏
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/spydaspider/microverse-projects/pull/6#pullrequestreview-1043833119>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXXCN5LEALJLM4L23YYL4EDVU3QTPANCNFSM537I6CIQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-19 17:30 UTC, merged

2022-10-11 07:22 UTC, spydaspider commented
Sir please I already have the eslinttrc.json for the Javascript in my
project. Please I want to know if there is another file I will add to that?

On Tue, 19 Jul 2022, 11:26 am spyda dick, ***@***.***> wrote:

> Thank you.
>
> On Tue, 19 Jul 2022, 11:22 am MUNEEB UL REHMAN, ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Hi @spydaspider <https://github.com/spydaspider> ,
>>
>> Good job so far! I see you put a lot of effort into this project.
>> However, there are some issues that you still need to work on to go to the
>> next project but you are almost there!
>> Highlights
>>
>>    - Descriptive PR
>>    - Good commit messages
>>
>> Required Changes ♻️
>>
>>    - Kindly add the linter files for javascript.
>>
>> *Check the comments under the review.*
>> Optional suggestions
>>
>> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
>> the approval of this PR. However, I strongly recommend you to take them
>> into account as they can make your code better.*
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me in your question so I can receive the
>> notification.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *As described in the Code reviews limits policy
>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>> limited number of reviews per project (check the exact number in your
>> Dashboard). If you think that the code review was not fair, you can request
>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>> ------------------------------
>>
>> In index.html
>> <https://github.com/spydaspider/microverse-projects/pull/6#discussion_r924373619>
>> :
>>
>> > +      <div class = "mobile-menu">
>>
>> +        <ul class = "nav-menu">
>>
>> +          <li class = "nav-item"><a href = "#headline">Portfolio</a></li>
>>
>> +          <li class = "nav-item"><a href = "#section-5">About</a></li>
>>
>> +          <li class = "nav-item"><a href = "#section-7">Contact</a></li>
>>
>> +        </ul>
>>
>> +        <div class="x-icon x-style">
>>
>> +          <span class = "bar-x"></span>
>>
>> +          <span class = "bar-x"></span>
>>
>> +          <span class = "bar-x"></span>
>>
>> +
>>
>>
>> Kindly follow the margin/paddings as per the Figma template.
>> Your design Figma design
>> [image: image]
>> <https://user-images.githubusercontent.com/33268927/179738056-03384a82-dc61-4bb1-bed5-6a43add0e460.png> [image:
>> image]
>> <https://user-images.githubusercontent.com/33268927/179737955-35514aaa-0fed-4192-90ac-7f72c6307794.png>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/spydaspider/microverse-projects/pull/6#discussion_r924374901>
>> :
>>
>> > @@ -11,15 +11,21 @@
>>
>>      <header id="headline">
>>
>>        <nav class="nav-container">
>>
>>          <div class="logo-text"><a href="#">Spyda</a></div>
>>
>> -        <div class="right-logo">
>>
>> -          <img
>>
>> -            src="images/menu-icon.png"
>>
>> -            alt="Menu Icon for toggle on small screens"
>>
>> -          />
>>
>> +      <div class = "mobile-menu">
>>
>> +        <ul class = "nav-menu">
>>
>> +          <li class = "nav-item"><a href = "#headline">Portfolio</a></li>
>>
>>
>> In the mobile menu, when I click on the portfolio link, it doesn't take
>> me to the portfolio section but to the top of the page. Consider fixing it.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/spydaspider/microverse-projects/pull/6#pullrequestreview-1043256625>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AXXCN5NZWPROQGVXAEXP2GLVU2FXPANCNFSM537I6CIQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>